default: first
endpoints:
    first:
        name: "First Polr Instance"
        url: http://first.domain.com
        api: api/v2
        key: 012365478901236547890123654789
    second:
        name: "Second Polr Instance"
        url: http://second.domain.com
        api: api/v2
        key: 789654123078965412307896541230
